language: ruby
cache: bundler
os: linux
dist: xenial
rvm:
  - 2.7.3
  - 2.6.7
  - 3.1.0
  - jruby-9.2.9.0
  - ruby-head
  - jruby-head
jobs:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
before_install:
  - gem update --system
  - gem install bundler -v 2.0.2
